
const projects =[
    {
        id: 1,
        name:"The Ocean Cleanup Project" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 1,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    {
        id: 2,
        name:"Solar Impulse" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 4,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    {
        id: 3,
        name:"Eden Reforestation Projects" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 2,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    {
        id: 4,
        name:"Great Green Wall Initiative" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 1,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    {
        id: 5,
        name:"The Green Building Council" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 1,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    {
        id: 6,
        name:"The Green Roof Initiative" ,
        thumbnail_1:"https://tse4.mm.bing.net/th?id=OIP.Mk_AvmfUthTbt8gA-Z7SHgHaEu&pid=Api&P=0&h=180",
        thumbnail_2:"https://www.thongtincongnghe.com/sites/default/files/images/2017/8/23/screen_shot_2017-08-23_at_2.39.48_pm.png",
        schedule:"We will implement and achieve the goal as quickly as possible. Then we will go out to eat and summarize the results of implementing the project.​",
        fund:1000,
        description:"This project focuses on removing plastic waste from the ocean by implementing a marine waste collection system.",
        city:"Da Nang",
        address:"Son Tra", 
        country_id:1,  
        topic_id: 1,
        status:1,
        begin: "10/16/2023",
        finish: "11/16/2023",
        created_at:"10/10/2023", 
    },
    
    
];

export default projects;